In [1]:
import numpy as np 

### 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type. 

In [6]:
arr = np.array([0,1,2,3,4,5], dtype = int)

In [7]:
arr

array([0, 1, 2, 3, 4, 5])

### 2. Given a NumPy array 'arr', check if its data type is float64. 
arr = np.array([1.5, 2.6, 3.7])

In [14]:
arr = np.array([1,2,3,4,5])
if (arr.dtype == np.float64):
    print('True')
   
else:
    print('False')

False


### 3.Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers

In [15]:
arr = np.array([3+4j, 2+5j, 7+3j], dtype = np.complex128)

In [16]:
arr

array([3.+4.j, 2.+5.j, 7.+3.j])

### 4. Convert an existing NumPy array 'arr' of integers to float32 data type

In [19]:
arr = np.array([1,2,3,4], dtype = int)
np.float32(arr)

array([1., 2., 3., 4.], dtype=float32)

### 5.Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision

In [27]:
arr = np.array([1.23456, 6.235784, 7.23416, 9.378727], dtype = np.float64)
np.float32(arr)

array([1.23456 , 6.235784, 7.23416 , 9.378727], dtype=float32)

### 6.Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type

In [44]:
arr = np.array([[1,2,3],[4,5,6]])
def array_attributes(arr):
    return f"(Array shape is: {arr.shape}) and (array size is: {arr.size}) and (array data type is: {arr.dtype})"


print(array_attributes(arr))

(Array shape is: (2, 3)) and (array size is: 6) and (array data type is: int32)


### 7.Create a function array_dimension that takes a NumPy array as input and returns its dimensionality

In [46]:
arr = np.array([[1,2,3],[4,5,6]])
def array_dimension(arr):
    return f"Array dimension is : {arr.ndim}"

print(array_dimension(arr))

Array dimension is : 2


### 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total 
### size in bytes.

In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
def item_size_info(arr):
    item_size = arr.itemsize
    item_bytes = arr.nbytes
    return f"Item size : {item_size}, Total size: {item_bytes}"


print(item_size_info(arr))

Item size : 4, Total size: 24


### 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
def array_strides(arr):
    return f"Array strides: {arr.strides}"

print(array_strides(arr))


Array strides: (12, 4)


### 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape 
### and strides of the array.

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
def array_shape_strides_relationship(arr):
    return f"Array strides: {arr.strides} , Array shape is : {arr.shape}"

print(array_shape_strides_relationship(arr))


Array strides: (12, 4) , Array shape is : (2, 3)


### 11.Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of 
### zeros with `n` elements

In [17]:
def create_zeros_array(n,m):
    return np.zeros((n,m))

create_zeros_array(3,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 12.Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D 
### NumPy array filled with ones of size `rows x cols`

In [15]:
def create_ones_matrix():
    rows = int(input("Enter number of rows :"))
    column = int(input("Enter number of rows :"))
    return np.ones((rows,column))

create_ones_matrix()

Enter number of rows : 4
Enter number of rows : 4


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

###                                              OR

In [16]:
def create_ones_matrix():
    rows = int(input("Enter number of rows :"))
    column = int(input("Enter number of rows :"))
    return np.full((rows,column) , 1)

create_ones_matrix()

Enter number of rows : 4
Enter number of rows : 4


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and 
### creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified 
### `step`.

In [14]:
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)


generate_range_array(0, 10, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

### 14.Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as 
### arguments and generates a NumPy array with num equally spaced values between `start` and `stop` 
### (inclusive).

In [20]:
def generate_linear_space():
    start = int(input("Enter starting value : "))
    stop = int(input('Enter stop value : '))
    num = int(input("How many value you take ? : "))
    return np.linspace(start, stop, num)


generate_linear_space()

Enter starting value :  1
Enter stop value :  20
How many value you take ? :  10


array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

### 15.. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square 
### identity matrix of size `n x n` using `numpy.eye`

In [22]:
def create_identity_matrix(n):
    return "The identity matrix is : ", np.eye(n)

create_identity_matrix(3)

('The identity matrix is : ',
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

### 16. Write a function that takes a Python list and converts it into a NumPy array

In [30]:
def convert_array(l):
    arr = np.array(l)
    return arr

l = [1,2,3,4,5]
convert_array(l)

array([1, 2, 3, 4, 5])

###  17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the 
### same data

In [29]:
arr = np.array([1,2,3,4,5,6])
brr  = arr.view()
print("Before viewing original array is :",arr)
print("Before viewing a array is :",brr)
arr[0] = 88
print("After viewing original array is : ", arr)
print("After viewing brr array is :", brr)

Before viewing original array is : [1 2 3 4 5 6]
Before viewing a array is : [1 2 3 4 5 6]
After viewing original array is :  [88  2  3  4  5  6]
After viewing brr array is : [88  2  3  4  5  6]


### 18.. Write a function that takes two NumPy arrays and concatenates them along a specified axis

In [36]:
arr = np.array([1,2,3,4])
brr = np.array([5,6,7,8])
np.concatenate((arr,brr) , axis = 0)



array([1, 2, 3, 4, 5, 6, 7, 8])

### 19.Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.
###  concatenate`.

In [46]:
arr = np.array([[1,2], [3,4]])
brr = np.array([[5], [6]])
np.concatenate((arr, brr), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

### 20.Write a function that vertically stacks multiple NumPy arrays given as a list

In [50]:
def multiply():
    arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
    brr = np.array([[4,3,6], [6,8,9], [1,5,4]])
    return "mutiply array is : ",arr @ brr

multiply()

('mutiply array is : ',
 array([[ 19,  34,  36],
        [ 52,  82,  93],
        [ 85, 130, 150]]))

###  21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) 
### with a given step size.

In [54]:
def create_array():
    start = int(input('Enter your starting value : '))
    stop = int(input('Enter your stoping value : '))
    step = float(input("Enter step size : "))
    return np.arange(start, stop, step)

create_array()

Enter your starting value :  1
Enter your stoping value :  10
Enter step size :  0.2


array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

### 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 
 ### (inclusive).

In [60]:
def equally_space(start, stop, spaced):
    
    return np.linspace(start, stop, spaced)

equally_space(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

### 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 
### 1000 (inclusive)

In [66]:
def logarithmically(start, stop, spaced):
    
    return np.logspace(start, stop, spaced, base = 10)

logarithmically(1, 1000, 5)

array([1.00000000e+001, 5.62341325e+250,             inf,             inf,
                   inf])

###  24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values 
### are random integers between 1 and 100

### 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column 
### with zeros. Use NumPy operations within the Pandas DataFrame

### 26. Access the 3rd element from the given NumPy array.
###  arr = np.array([10, 20, 30, 40, 50])

In [63]:
arr = np.array([10, 20, 30, 40, 40])
arr[2]

30

### 27. Retrieve the element at index (1, 2) from the 2D NumPy array.
   arr_2d = np.array([[1, 2, 3],

 [4, 5, 6],

 [7, 8, 9]])

In [64]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr_2d[1][2]

6

###  28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
### arr = np.array([3, 8, 2, 10, 5, 7])

In [97]:
arr = np.array([3, 8, 2, 10, 5, 7])
print(arr[(arr > 5)])

[ 8 10  7]


### 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
### arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[2:5]

array([3, 4, 5])

 ### 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
 arr_2d = np.array([[1, 2, 3],

 [4, 5, 6],

 [7, 8, 9]])


In [78]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr[0:2 , [1,2]]

array([[2, 3],
       [5, 6]])

### 31. Write a NumPy function to extract elements in specific order from a given 2D array based on indices 
### provided in another array.

In [84]:
def another_array(arr ):
    index_array = np.array([arr[0][1], arr[1][2], arr[2][2]])
    return index_array
    
    
another_array(arr = np.array([[10, 20, 30], [40, 30, 10], [50, 90, 60]]))

array([20, 10, 60])

###  32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using 
### boolean indexing.

In [85]:
arr = np.array([10, 3, 6, 50, 40, 5, 9, 70])
print(arr[arr > 5])

[10  6 50 40  9 70]


###  33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three 
### separate arrays for each dimension

In [88]:
import numpy as np

def extract_from_3d(arr, idx0, idx1, idx2):
    return arr[idx0, idx1, idx2]


arr = np.array([
    [[10, 11, 12],
     [13, 14, 15]],
    
    [[20, 21, 22],
     [23, 24, 25]],
    
    [[30, 31, 32],
     [33, 34, 35]]
])

# Indices to extract elements from: (0,0,1), (1,1,2), (2,0,0)
idx0 = np.array([0, 1, 2])  # depth indices
idx1 = np.array([0, 1, 0])  # row indices
idx2 = np.array([1, 2, 0])  # column indices

result = extract_from_3d(arr, idx0, idx1, idx2)
print("Extracted elements:", result)


Extracted elements: [11 25 30]


###  34. Write a NumPy function that returns elements from an array where both two conditions are satisfied 
### using boolean indexing

In [99]:
arr = np.array([10, 20, 5, 8, 100, 9, 22])
def two_condition_satisfied(arr):
    return arr[(arr > 5) & (arr % 2 !=0)]




two_condition_satisfied(arr)

array([9])

### 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided 
### in separate arrays

###  36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [103]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr + 5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

###  37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the 
### corresponding element in arr1 using NumPy broadcasting

In [112]:
arr1 = np.array([[2, 3, 4]])

arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

result = arr1.T * arr2  #[ Here use transpose of matrix because of our 1st array contain 3 column but 2nd array have 4 colunm , here particular mention 
# index wise multiplication , so transpose use]
print(result)

[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


###  38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using 
### NumPy broadcasting.

In [115]:
arr1 = np.array([[1, 2, 3, 4]])

arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])
result = arr1 + arr2
print(result)

[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]


###  39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy 
### broadcasting.

In [125]:
arr1 = np.array([[1], 
                 [2], 
                 [3]])

arr2 = np.array([1,2,3])
result_add = arr1.T + arr2
print(result_add)


[[2 4 6]]


###  40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy 
### broadcasting. Handle the shape incompatibility.

In [132]:
arr1 = np.array([[1, 2, 3],
                [4, 5, 6]])

arr2 = np.array([[1, 2],
                [3, 4]])
arr1_reshape = arr1.reshape(2,3,1)    # shape (2, 3, 1) chage array shape
arr2_reshape = arr2.reshape(2,1,2)    # shape (2, 1, 2) change array shape
result_multiply = arr1_reshape * arr2_reshape
print(result_multiply)

[[[ 1  2]
  [ 2  4]
  [ 3  6]]

 [[12 16]
  [15 20]
  [18 24]]]


###  41. Calculate column-wise mean for the given array:
 ### arr = np.array([[1, 2, 3], [4, 5, 6]])

In [138]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
column_mean = np.mean(arr, axis = 0)

print('column wise mean is :',column_mean)


column wise mean is : [2.5 3.5 4.5]


### 42. Find maximum value in each row of the given array:
 ### arr = np.array([[1, 2, 3], [4, 5, 6]])

In [148]:
arr = np.array([[1, 2, 3],
               [4, 5, 6]])
row1_max = np.max(arr[0])
row2_max = np.max(arr[1])
print('Row 1 maximum value is : ',row1_max)
print('Row 2 maximum value is : ',row2_max)


Row 1 maximum value is :  3
Row 2 maximum value is :  6


### OR

In [149]:
arr = np.array([[1, 2, 3],
               [4, 5, 6]])
result_max = np.max(arr,  axis = 1)
print('Row wise maximum value is :',result_max)

Row wise maximum value is : [3 6]


### 43. For the given array, find indices of maximum value in each column.
 ### arr = np.array([[1, 2, 3], [4, 5, 6]])

In [152]:
arr = np.array([[1, 2, 3],
               [4, 5, 6]])
result_index = np.argmax(arr, axis = 0)
print('The maximum value index are : ',result_index)

The maximum value index are :  [1 1 1]


###  44. For the given array, apply custom function to calculate moving sum along rows.
### arr = np.array([[1, 2, 3], [4, 5, 6]])

In [163]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

def moving_sum_rowwise(array, window=2):
    return np.array([np.convolve(row, np.ones(window), 'valid') for row in array])  # (1+2), (2+3)  That is moving sum
                                                                                     # (4+5) (5+6)

result = moving_sum_rowwise(arr, window=2)
print("Row-wise moving sum (window=2):\n", result)


Row-wise moving sum (window=2):
 [[ 3.  5.]
 [ 9. 11.]]


###  45. In the given array, check if all elements in each column are even.
 ### arr = np.array([[2, 4, 6], [3, 5, 7]])


In [169]:
import numpy as np

arr = np.array([[2, 4, 6],
                [3, 5, 7]])

# Check if each element is even
even_check = arr % 2 == 0
print(even_check)


[[ True  True  True]
 [False False False]]


### 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the 
### reshaped matrix.
###  original_array = np.array([1, 2, 3, 4, 5, 6])

In [180]:
arr = np.array([1, 2, 3, 4, 5, 6])

def convert_matrix(arr, m, n):
    brr = arr.reshape(m, n)
    mat = np.matrix(brr)
    return mat

convert_matrix(arr , 2, 3)

matrix([[1, 2, 3],
        [4, 5, 6]])

###  47. Create a function that takes a matrix as input and returns the flattened array.
###  input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [183]:
input_matrix = np.array([[1, 2, 3], 
                         [4, 5, 6]])
def flattened_array(arr):
    return arr.flatten()

flattened_array(input_matrix)

array([1, 2, 3, 4, 5, 6])

###  48. Write a function that concatenates two given arrays along a specified axis.
### array1 = np.array([[1, 2], [3, 4]])
###  array2 = np.array([[5, 6], [7, 8]])

In [189]:
array1 = np.array([[1, 2], 
                   [3, 4]])

array2 = np.array([[5, 6], 
                   [7, 8]])

def concatenate(array1, array2):
    return np.concatenate((array1, array2), axis = 0) # concatenate along column axis



concatenate(array1, array2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

#### OR

In [190]:
array1 = np.array([[1, 2], 
                   [3, 4]])

array2 = np.array([[5, 6], 
                   [7, 8]])

def concatenate(array1, array2):
    return np.concatenate((array1, array2), axis = 1) # concatenate along row axis 



concatenate(array1, array2)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

###  49. Create a function that splits an array into multiple sub-arrays along a specified axis.
### original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [210]:
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
def split(arr):
    
    return 'sub array are :',arr[0], arr[1], arr[2]

print('Original_array is :\n',original_array)
split(original_array)

Original_array is :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


('sub array are :', array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

###  50. Write a function that inserts and then deletes elements from a given array at specified indices.
###  original_array = np.array([1, 2, 3, 4, 5])
###  indices_to_insert = [2, 4]
###  values_to_insert = [10, 11]
###  indices_to_delete = [1, 3]

In [212]:


original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]


def insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    modified_array = np.insert(original_array, indices_to_insert, values_to_insert)
    
    modified_array = np.delete(modified_array, indices_to_delete)
    return modified_array






result = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print("Final array:", result)


Final array: [ 1 10  4 11  5]


###  51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. 
### Perform element-wise addition between `arr1` and `arr2`.

In [12]:
arr1 = np.arange(1,11,1)
arr2 = np.random.randint(1,10,(1,10))
result_array = arr1 + arr2

print(result_array)

[[ 5  3  6 13 10  9 13 12 11 13]]


###  52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers 
### from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [17]:
arr1 = np.arange(10,0,-1)  # array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])
arr2 = np.arange(0,10,1)   # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
result_subtract = arr2 - arr1

print(result_subtract)

[-10  -8  -6  -4  -2   0   2   4   6   8]


###  53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. 
### Perform element-wise multiplication between `arr1` and `arr2`.

In [22]:
arr1 = np.random.random_sample(5)  # array([0.11851327, 0.34520893, 0.09959498, 0.23845324, 0.03733064])
arr2 = np.random.randint(1,5,(5))  # array([1, 3, 4, 3, 2])
result_multiply = arr1 * arr2

print(result_multiply)

[2.33063668 2.78800518 1.11420059 0.00481745 0.06005346]


###  54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 
### to 5. Perform element-wise division of `arr1` by `arr2`.

In [23]:
arr1 = np.array([2, 4, 6, 8, 10])
arr2 = np.array([1, 2, 3, 4, 5])
result_division = arr1 / arr2

print(result_division)

[2. 2. 2. 2. 2.]


###  55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers 
### reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [36]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
result_power = np.power(arr1, arr2)

print(result_power)

[ 1 16 27 16  5]


###  56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
###  arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [49]:
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

def count(arr , n):
    count = 0
    for i in arr:
        if (i == n) :
            count = count + 1
    return count


result = count(arr, n= 'hello')
print('hello occurrences is ',result,'times')

hello occurrences is  3 times


###  57. Write a function that extracts uppercase characters from a NumPy array of strings.
###  arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])


In [5]:
import numpy as np
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

def uppercase_extracts(arr):
    result = []
    for i in arr:
        if i.isupper():
            result.append(i)
    return result
        


print(uppercase_extracts(arr))



['GPT']


### 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
###  arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [ ]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

###  59. Write a function that concatenates strings in a NumPy array element-wise.
###  arr1 = np.array(['Hello', 'World'])
###  arr2 = np.array(['Open', 'AI'])

In [11]:
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

def concatenate_string(arr1, arr2):
    return np.concatenate((arr1, arr2), axis = 0)
    

print(concatenate_string(arr1, arr2))

['Hello' 'World' 'Open' 'AI']


###  60. Write a function that finds the length of the longest string in a NumPy array.
### arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
###  arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

###  61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and 
### standard deviation of the dataset using NumPy's functions.

In [17]:
arr = np.linspace(1, 1000, 100)
mean = np.mean(arr)
median = np.median(arr)
variance = np.var(arr)
standard_deviation =np.std(arr)

print('The give range mean is : ',mean)
print('The give range median is : ',median)
print('The give range variance is : ',variance)
print('The give range standard_deviation is : ',standard_deviation)

The give range mean is :  500.5
The give range median is :  500.5
The give range variance is :  84846.88636363637
The give range standard_deviation is :  291.2848886633777


###  62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the 
### dataset.

In [20]:
arr = np.linspace(1, 101, 50)
percentile_25 = np.percentile(arr, 25)
percentile_75 = np.percentile(arr, 75)

print('25% is :',percentile_25)
print('75% is :',percentile_75)

25% is : 26.0
75% is : 76.0


###  63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these 
### arrays using NumPy's `corrcoef` function.

###  64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [27]:
mat1 = np.matrix([[1, 2, 3],
                  [4, 5, 6]])

mat2 = np.matrix([[4, 7, 2], 
                  [5, 7, 9], 
                  [1, 4, 3]])

multiply = np.dot(mat1, mat2)

print(multiply)

[[17 33 29]
 [47 87 71]]


### 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th 
### percentiles along with the first and third quartiles.

In [30]:

arr = np.random.randint(10, 1001, 50)

# Calculate percentiles
percentile_10 = np.percentile(arr, 10)
percentile_50 = np.percentile(arr, 50)  # median
percentile_90 = np.percentile(arr, 90)


q1 = np.percentile(arr, 25)  # First quartile
q3 = np.percentile(arr, 75)  # Third quartile

# Display results
print("Array:", arr)
print('\n')
print("10th Percentile:", percentile_10)
print("50th Percentile (Median):", percentile_50)
print("90th Percentile:", percentile_90)
print("First Quartile (Q1):", q1)
print("Third Quartile (Q3):", q3)


Array: [144 113 566 484 610 223 582 670  79 770 713 290 863 565 181 803 720 559
 605 903 932  95 744 258 617 145 730 905 995 211 993 571 770 560 902 358
 670 579 818 701 368 399 458 912 555 455 438 979 189 167]


10th Percentile: 164.8
50th Percentile (Median): 575.0
90th Percentile: 905.7
First Quartile (Q1): 360.5
Third Quartile (Q3): 763.5


###   66. Create a NumPy array of integers and find the index of a specific element.

In [7]:
arr = np.array([1,2,3,4,5,6,200], dtype = int)
a = 190
index = np.searchsorted(arr, a)
print('original array is :', arr)
print('The specific element index is : ',index)

original array is : [  1   2   3   4   5   6 200]
The specific element index is :  6


###  67. Generate a random NumPy array and sort it in ascending order.

In [10]:
arr = np.random.randint(1,20,10)
sorted = np.sort(arr)
print('Random array is :',arr)
print('sorted array is :',sorted)

Random array is : [15  3  4  1  5  9  9 18 13 18]
sorted array is : [ 1  3  4  5  9  9 13 15 18 18]


###  68. Filter elements >20  in the given NumPy array.
###  arr = np.array([12, 25, 6, 42, 8, 30])

In [14]:
arr = np.array([12, 25, 6, 42, 8, 30])
brr = arr[(arr>20)]
print('original array is :',arr)
print('elements >20 are :',brr)

original array is : [12 25  6 42  8 30]
elements >20 are : [25 42 30]


###  69. Filter elements which are divisible by 3 from a given NumPy array.
###  arr = np.array([1, 5, 8, 12, 15])

In [24]:
arr = np.array([1, 5, 8, 12, 15])
result = arr[(arr %3 ==0)]

print('original array is :',arr)
print('divisible by 3 element are :',result)

original array is : [ 1  5  8 12 15]
divisible by 3 element are : [12 15]


### OR

In [26]:
arr = np.array([1, 5, 8, 12, 15])
result2 = []
for i in arr:
    if i%3 ==0:
        result2.append(i)

print('divisible by 3 element are :',result2)

divisible by 3 element are : [12, 15]


###  70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
###  arr = np.array([10, 20, 30, 40, 50])

In [35]:
arr = np.array([10, 20, 30, 40, 50])
result = []
for i in arr:
    if i>=20 and i<=40:
        result.append(i)

print(result)

[20, 30, 40]


###  71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
### arr = np.array([1, 2, 3])

### 72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
###  arr = np.array([1, 2, 3], dtype=np.int32)

###  73. For the given NumPy array, swap its byte order without modifying the original array using 
### `newbyteorder()`.
###  arr = np.array([1, 2, 3], dtype=np.int32)

###  74. For the given NumPy array and swap its byte order conditionally based on system endianness using 
### `newbyteorder()`.
###  arr = np.array([1, 2, 3], dtype=np.int32)

###  75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` 
### attribute `byteorder`.
###  arr = np.array([1, 2, 3], dtype=np.int32)

###  76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify 
### an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [36]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
copy_arr = arr1
copy_arr[0] = 15
print('original array is :',arr1)
print('modified array is ',copy_arr)

original array is : [15  2  3  4  5  6  7  8  9 10]
modified array is  [15  2  3  4  5  6  7  8  9 10]


### 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from 
### the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

###  78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice 
### `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

### 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view 
### `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it 
### reflects changes in the original `orig_array`.

###  80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of 
### elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

###  81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction 
### operations between them.

In [49]:
mat1 = np.matrix([[1, 2, 3], 
                  [5, 6, 7], 
                  [8, 9, 10]])

mat2 = np.matrix([[11, 12, 13],
                  [10, 16, 17], 
                  [18, 19, 20]])

print('Matrix addition is \n:', mat1 + mat2)
print('Matrix addition is \n:', mat1 - mat2)

Matrix addition is 
: [[12 14 16]
 [15 22 24]
 [26 28 30]]
Matrix addition is 
: [[-10 -10 -10]
 [ -5 -10 -10]
 [-10 -10 -10]]


###  82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [47]:
arr1 = np.array([[1, 2], 
                 [3, 4], 
                 [5,6]])
arr2 = np.array([[6, 4, 3, 7],
                 [9, 2, 4, 6]])
arr1 @ arr2

array([[24,  8, 11, 19],
       [54, 20, 25, 45],
       [84, 32, 39, 71]])

###  83. Create a matrix `E` and find its transpose.

In [46]:
arr = np.array([[1], 
                [2], 
                [3], 
                [4]])

print('Transpose matrix is :',arr.T)

Transpose matrix is : [[1 2 3 4]]


###  84. Generate a square matrix `F` and compute its determinant.

In [42]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print('Determinat is :',np.linalg.det(arr))

Determinat is : 6.66133814775094e-16


### 85. Create a square matrix `G` and find its inverse

In [43]:
arr = np.eye(3)
print('original array is \n:',arr)
print("inverse matrix is \n:",np.linalg.inv(arr))

original array is 
: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
inverse matrix is 
: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
